import { Content, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "oussama taright",
  description: "Generated by create next app",
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <navbar style={{ display: "flex", gap: "1rem",  background: "#f0f0f0", padding: "20px" , width: "100%",  fontSize: "30px", borderRadius: "2px", border  : "1px solid #ccc", justifyContent: "center", alignItems: "center", color: "black"}}>
      <Link href="/home">Home</Link>
      <Link href="/lll">About</Link>
      <Link href="/contact"> Contact</Link>
      <Link href="/"> return</Link>

      </navbar> 
        {children}
      </body>
    </html>
  );
}



